sudo: required
language: generic
servives:
    - docker

before_install:
    - docker build -t rafaelhd/react-docker-demo -f Dockerfile.dev .

script:
    - docker run -e CI=true rafaelhd/react-docker-demo npm run test    